kind: Service # Defines to create Service type Object
apiVersion: v1
metadata:
  name: demoservice
spec:
  ports:
    - port: 8443 # Containers port exposed
      targetPort: 8443 # Pods port
  selector:
    name: deployment # Apply this service to any pods which has the specific label
  # type: ClusterIP # Specifies the service type i.e ClusterIP or NodePort
  type: NodePort # Specifies the service type i.e ClusterIP or NodePort to expose on the internet
