kind: Deployment
apiVersion: apps/v1
metadata:
  name: mydeployments
spec:
  replicas: 2
  selector:
    matchLabels:
      name: deployment
  template:
    metadata:
      name: testpod
      labels:
        name: deployment
    spec:
      containers:
        - name: c00
          image: centos
          command:
            [
              "/bin/bash",
              "-c",
              "while true; do echo love your self; sleep 5; done",
            ]
